# input

This scripts creates the input dataset for our disperseR simulations.

```{r, include = FALSE}
library(tidyverse)
library(magrittr)
library(lubridate)
library(sf)
library(maps)
```

* Read fracking well data

```{r}
input <- read_csv("./tx-tracts-vnf-nightly.csv")
input %<>%
  mutate(STATEFP = as.character(STATEFP), 
         #COUNTYFP = as.character(COUNTYFP), 
         #TRACTCE = as.character(TRACTCE),
         GEOID = as.character(GEOID)) %>% 
  rename(flares_per_day = flares)
head(input)
```

```{r}
summary(input) 
```

* Get centroids

```{r}
states_sf <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
head(states_sf)
crs_ <- st_crs(states_sf)
```

<!-- ```{python} -->
<!-- import wget -->
<!-- from zipfile import ZipFile -->
<!-- import os -->

<!-- url = 'https://www2.census.gov/geo/tiger/TIGER2016/TRACT/tl_2016_48_tract.zip' -->
<!-- wget.download(url, os.path.expanduser('~/tmp')) -->
<!-- file_name = os.path.expanduser('~/tmp/tl_2016_48_tract.zip') -->
<!-- ZipFile(file_name, 'r').extractall(os.path.expanduser('~/tmp/tl_2016_48_tract/')) -->
<!-- os.system("ls ~/tmp/tl_2016_48_tract/") -->
<!-- ``` -->

```{r, include=FALSE}
#### read tracts shapefile
tracts_sf <- st_read("~/tmp/tl_2016_48_tract/tl_2016_48_tract.shp")
tracts_sf <- tracts_sf %>% 
  dplyr::filter(STATEFP == "48")
tracts_sf <- st_transform(tracts_sf, crs_)
head(tracts_sf)
```

```{r}
geoid_ <- unique(input$GEOID)
centroids_sf <- tracts_sf %>% 
  filter(GEOID %in% geoid_)
head(centroids_sf)
```

```{r}
ggplot() + 
  geom_sf(data = filter(states_sf, ID == "texas")) + 
  geom_sf(data = centroids_sf, fill = "blue")
```

```{r}
centroids_sf <- centroids_sf %>% 
  st_centroid(centroids_sf)

ggplot() + 
  geom_sf(data = filter(states_sf, ID == "texas")) + 
  geom_sf(data = centroids_sf, color = "red")
```

```{r}
coords <- as_tibble(st_coordinates(centroids_sf)) %>% 
  rename(Latitude = Y, 
         Longitude = X)
centroids_sf <- bind_cols(centroids_sf, coords)
head(centroids_sf)
```

* Prepare input data for disperser

```{r}
input %<>% 
  left_join(centroids_sf %>% 
              st_drop_geometry() %>% 
              select(GEOID, Latitude, Longitude))
start_hour_ <- lapply(input$flares_per_day, function(x) floor(seq(6,17,12/x)))
input$start_hour = start_hour_
input <- unnest(input, cols = c(start_hour))
head(input)
```

```{r}
dim(input)
input %<>% 
  group_by_all() %>% 
  summarise(n = n())
dim(input)
```

```{r}
write_rds(input, "./input.rds")
```

```{r}
#number of simulations per year
input %>% 
  group_by(year(date)) %>% 
  summarise(n_sim = n(), 
            n_flares = sum(n))
```
