# input

```{r}
library(tidyverse)
library(magrittr)
library(lubridate)
library(sf)
library(maps)
library(gridExtra)
library(cowplot)
library(RColorBrewer)
library(ggthemes)
library(tidycensus)
library(leaflet)
census_api_key('ad9a7887ee64724384b5cefd5656ff352288a946')
```

* Read dispersion data

```{r}
input <- read_rds("../linked_counties.rds")
input %<>%
  rename(fips = geoid, 
         particles = N) %>% 
  mutate(year = as.integer(str_sub(month,1, 4)), 
         month = as.integer(str_sub(month,5, -1)), 
         date = ymd(sprintf("%04d%02d01", year, month))) %>% 
  na.omit()
head(input)
```

```{r}
dim(input)
summary(input) 
```

```{r}
length(unique(input$fips))
```

```{r}
length(unique(input$date))
```

```{r}
input %>% 
  group_by(date) %>% 
  summarise(particles = sum(particles))
```

```{r}
sum(input$particles)
```

* particles ts

```{r}
input %<>% 
  mutate(yyyy_mm = format(as.Date(date), "%Y_%m"))

input %>% 
  group_by(yyyy_mm) %>% 
  summarise(particles = sum(particles)) %>% 
ggplot() + 
  geom_line(aes(x = ym(yyyy_mm), y = particles, color = particles)) +
  theme_cowplot()
```

## Explore counties

```{r}
states_sf <- st_as_sf(map("state", plot = FALSE, fill = TRUE))
head(states_sf)
crs_ <- st_crs(states_sf)
```

```{r}
# Estimate!!Total
county_sf <- get_acs(year = 2018,
                     geography = "county",
                     variables = "B01001_001",
                     state = "TX",
                     geometry = TRUE)

county_sf %<>% 
  rename(fips = GEOID, 
         pop = estimate, 
         county_name = NAME) %>% 
  select(fips, county_name, pop)

head(county_sf)
```

* particles map

```{r}
fips_ <- unique(input$fips)
sum(!fips_ %in% county_sf$fips) # <- all GEOIDs in shapefile

county_sf %>% 
  left_join(input %>% 
              group_by(fips) %>% 
              summarise(particles = sum(particles))) %>% 
  filter(!is.na(particles)) %>% 
ggplot() + 
  geom_sf(data = filter(states_sf, ID == "texas")) + 
  geom_sf(aes(fill = particles)) +
  theme_map()
```

* county_particles_maps summary

```{r}
particles_ <- input %>% 
  group_by(yyyy_mm, fips) %>% 
  summarise(particles = sum(particles)) %>% 
  pull(particles)
myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
sc <- scale_fill_gradientn(colours = myPalette(100), 
                             limits=c(min(particles_), max(particles_)))
  
county_particles_maps <- list()
yyyy_mm_ <- sort(unique(input$yyyy_mm))
x <- yyyy_mm_[1]
p <- county_sf %>% 
    left_join(input %>% 
                filter(yyyy_mm == x) %>% 
                group_by(fips) %>% 
                summarise(particles = sum(particles))) %>% 
    filter(!is.na(particles)) %>% 
    ggplot() +
    geom_sf(data = filter(states_sf, ID == "texas")) +
    geom_sf(aes(fill = particles)) + 
    sc
county_particles_maps[["1"]] <- get_legend(p)
for(x in yyyy_mm_) {
  county_particles_maps[[x]] <- county_sf %>% 
    left_join(input %>% 
                filter(yyyy_mm == x) %>% 
                group_by(fips) %>% 
                summarise(particles = sum(particles))) %>% 
    filter(!is.na(particles)) %>% 
    ggplot() +
    geom_sf(data = filter(states_sf, ID == "texas")) +
    geom_sf(aes(fill = particles)) + 
    sc + 
    theme_map() +
    theme(legend.position = "none") + 
    labs(title = x)
}
county_particles_maps <- marrangeGrob(county_particles_maps, 
                           nrow = 4, ncol = 2, 
                           left = "", top = "particles per county per yyyy-mm")
ggsave("./particles_output/county_particles_maps.pdf", 
       county_particles_maps, width = 15, height = 25, units = "cm")
```

* concentration map

```{r}
county_sf$area_km2 <- as.numeric(st_area(county_sf) / 1e6)

county_sf %>% 
  left_join(input %>% 
              group_by(fips) %>% 
              summarise(particles = sum(particles))
            ) %>% 
  filter(!is.na(particles)) %>% 
  mutate(concentration = particles / area_km2,
         concentration_per_cap = particles / area_km2 / pop) %>% 
ggplot() + 
  geom_sf(data = filter(states_sf, ID == "texas")) + 
  geom_sf(aes(fill = concentration)) +
  theme_map()
```

## Explore cbsa (Core Based Statistical Areas)

```{r}
cbsa <- read_csv("../data/cbsa.csv")
head(cbsa)

cbsa %<>% 
  mutate(cbsa = as.character(cbsa), 
         fips = as.character(fips))
```

```{r}
sum(!county_sf$fips %in% cbsa$fips) # <- there are counties that are not port of a cbsa 
```

```{r}
cbsa_sf <- county_sf %>% 
  left_join(cbsa) %>% 
  mutate(cbsa = if_else(is.na(cbsa), fips, cbsa), 
         cbsa_name = if_else(is.na(cbsa_name), county_name, cbsa_name)) %>% 
  group_by(cbsa, cbsa_name) %>% 
  summarise(pop = sum(pop), 
            area_km2 = sum(area_km2))

cbsa_sf %>% 
  st_drop_geometry()
```

```{r}
unique(input$fips[!input$fips %in% cbsa$fips])

input %<>% 
  left_join(cbsa) %>% 
  mutate(cbsa = if_else(is.na(cbsa), fips, cbsa), 
         cbsa_name = if_else(is.na(cbsa_name), name, cbsa_name))

head(input)
```

```{r}
cbsa_sf %<>% 
  left_join(input %>% 
              group_by(cbsa) %>% 
              summarise(particles = sum(particles))) %>% 
  filter(!is.na(particles)) %>%
  mutate(concentration = particles / area_km2, 
         concentration_per_cap = particles / area_km2 / pop)
```

```{r}
map <- cbsa_sf %>% 
  as("Spatial")

pal <- colorQuantile("Blues", map$particles, n = 10)

leaflet() %>% 
  leaflet::addProviderTiles(provider = "OpenStreetMap") %>% 
  addPolygons(data = map, 
              weight = 0.5, 
              color = "black",
              fillColor = pal(map@data$particles), 
              fillOpacity = 1, 
              label = ~ cbsa_name)
```

* concentration_per_cap

```{r}
pal <- colorQuantile("Blues", map$concentration_per_cap, n = 10)

leaflet() %>% 
  leaflet::addProviderTiles(provider = "OpenStreetMap") %>% 
  addPolygons(data = map, 
              weight = 0.5, 
              color = "black",
              fillColor = pal(map@data$concentration_per_cap), 
              fillOpacity = 1, 
              label = ~ cbsa_name)
```

* cbsa_particles_ts summary

```{r}
input_cbsa <- input %>% 
  group_by(yyyy_mm, cbsa) %>% 
  summarise(particles = sum(particles))
myPalette <- colorRampPalette(rev(brewer.pal(11, "Spectral")))
sc <- scale_color_gradientn(colours = myPalette(100), 
                             limits=c(min(input_cbsa$particles), 
                                      max(input_cbsa$particles)))

cbsa_particles_ts <- list()
cbsa_sf %<>% 
  arrange(desc(particles_per_cap))
#i = 1
for(i in 1:nrow(cbsa_sf)) {
  cbsa_ <- cbsa_sf$cbsa[i]
  cbsa_name_ <- cbsa_sf$cbsa_name[i]
  particles_per_cap_ <- cbsa_sf$particles_per_cap[i]
  
  map <- cbsa_sf %>% 
    filter(cbsa == cbsa_) %>% 
    ggplot() + 
    geom_sf(data = filter(states_sf, ID == "texas")) + 
    geom_sf(aes(fill = cbsa_)) + 
    theme_map() +
    theme(legend.position = "none") + 
    labs(title = "particles per cap:", 
         subtitle = round(particles_per_cap_, digits = 2))
  
  ts <- input_cbsa %>% 
    filter(cbsa == cbsa_) %>% 
    ggplot() +
    geom_point(aes(x = ym(yyyy_mm), y = particles, color = particles)) + 
    geom_line(aes(x = ym(yyyy_mm), y = particles, color = particles)) + 
    sc + 
    theme_cowplot() + 
    xlim(c(min(ym(input_cbsa$yyyy_mm)), max(ym(input_cbsa$yyyy_mm)))) +
    theme(legend.position = "none") + 
    labs(title = cbsa_name_, x = "")
  
  cbsa_particles_ts[[i]] <- plot_grid(map, ts, ncol = 2, rel_widths = c(0.2, 0.8))
}
cbsa_particles_ts <- marrangeGrob(cbsa_particles_ts, 
                           nrow = 3, ncol = 1, 
                           left = "", top = "CBSA's sorted by particles per capita")
ggsave("./particles_output/cbsa_particles_ts.pdf", 
       cbsa_particles_ts, width = 15, height = 25, units = "cm")
```
