# Parcels checkpoint

```{r, warning=F, message=F}
library(tidyverse)
library(magrittr)
library(lubridate)
```

```{r}
disperser_input <- read_rds("../data/jobs_input/disperser_input.rds")

#### number of files disperser will create for each year month
disperser_input %>% 
  group_by(year, month) %>% 
  summarise(n = n())
```


<!-- # daily_comparison -->

<!-- ```{r setup, include=FALSE} -->
<!-- knitr::opts_chunk$set(echo = F) -->
<!-- ``` -->

<!-- ```{r, include=FALSE} -->
<!-- library(tidyverse) -->
<!-- library(magrittr) -->
<!-- library(lubridate) -->
<!-- library(sf) -->
<!-- library(maps) -->
<!-- library(gridExtra) -->
<!-- library(cowplot) -->
<!-- library(RColorBrewer) -->
<!-- library(ggthemes) -->
<!-- library(tidycensus) -->
<!-- library(viridis) -->
<!-- #### include your census api key -->
<!-- #census_api_key('<your_key>', install = TRUE) -->
<!-- ``` -->

<!-- ```{r, include=FALSE} -->
<!-- #### Read fracking well data -->
<!-- flares <- read_csv("../data/input/tx-tracts-vnf-nightly.csv") -->

<!-- flares %<>% -->
<!--   mutate(STATEFP = as.character(STATEFP),  -->
<!--          #COUNTYFP = as.character(COUNTYFP),  -->
<!--          #TRACTCE = as.character(TRACTCE), -->
<!--          GEOID = as.character(GEOID),  -->
<!--          year = year(date),  -->
<!--          month = month(date)) -->

<!-- length(unique(flares$GEOID)) -->
<!-- summary(flares$flares) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- ## Read particles data -->
<!-- dispersion <- lapply(2015:2020,  -->
<!--                      function(y) read_rds(paste0("../data/output/polygon_parcels_",  -->
<!--                                                 y, ".rds"))) -->
<!-- dispersion <- bind_rows(dispersion) -->

<!-- length(unique(dispersion$id)) -->
<!-- summary(dispersion$count) -->
<!-- ``` -->

<!-- ```{r, include=FALSE} -->
<!-- #### read state shapefile -->
<!-- states_sf <- st_as_sf(map("state", plot = FALSE, fill = TRUE)) -->
<!-- crs_ <- st_crs(states_sf) -->
<!-- ``` -->

<!-- <!-- ```{python} --> -->
<!-- <!-- import wget --> -->
<!-- <!-- from zipfile import ZipFile --> -->
<!-- <!-- import os --> -->

<!-- <!-- url = 'https://www2.census.gov/geo/tiger/TIGER2016/TRACT/tl_2016_48_tract.zip' --> -->
<!-- <!-- wget.download(url, os.path.expanduser('~/tmp')) --> -->
<!-- <!-- file_name = os.path.expanduser('~/tmp/tl_2016_48_tract.zip') --> -->
<!-- <!-- ZipFile(file_name, 'r').extractall(os.path.expanduser('~/tmp/tl_2016_48_tract/')) --> -->
<!-- <!-- os.system("ls ~/tmp/tl_2016_48_tract/") --> -->
<!-- <!-- ``` --> -->

<!-- ```{r, include=FALSE} -->
<!-- #### read tracts shapefile -->
<!-- tracts_sf <- st_read("../data/input/tl_2016_48_tract/tl_2016_48_tract.shp") -->
<!-- tracts_sf %<>%  -->
<!--   dplyr::filter(STATEFP == "48") %>%  -->
<!--   mutate(area = ALAND / 1e6) #ALAND in tiger filers is reported in sq meters -->
<!-- tracts_sf <- st_transform(tracts_sf, crs_) -->
<!-- ``` -->

<!-- ```{r, include=FALSE} -->
<!-- #### get tracts population -->
<!-- v18 <- load_variables(2018, "acs5", cache = TRUE) -->
<!-- # View(v18) -->

<!-- # Estimate!!Total -->
<!-- tract_acs <- get_acs(year = 2018, -->
<!--                      geography = "tract", -->
<!--                      variables = "B01001_001", -->
<!--                      state = "TX", -->
<!--                      geometry = FALSE) -->
<!-- tract_acs %<>%  -->
<!--   rename(pop = estimate) -->
<!-- ``` -->

<!-- ```{r, include=FALSE} -->
<!-- #### join tracts and population -->
<!-- # all shapefile GEOIDs in acs query -->
<!-- # sum(!tracts_sf$GEOID %in% tract_acs$GEOID)  -->

<!-- tracts_sf %<>%  -->
<!--   left_join(tract_acs %>%  -->
<!--               select(GEOID, pop)) -->
<!-- ``` -->

<!-- ```{r, include=FALSE} -->
<!-- #### read cbsa data -->
<!-- cbsa <- read_csv("../data/input/cbsa.csv") -->

<!-- cbsa %<>%  -->
<!--   mutate(cbsa = as.character(cbsa),  -->
<!--          fips = as.character(fips)) -->
<!-- ``` -->

<!-- ```{r, include=FALSE} -->
<!-- #### join tracts_sf and cbsa data -->
<!-- tracts_sf %<>%  -->
<!--   mutate(fips = paste0(STATEFP, COUNTYFP)) -->

<!-- # some tracts are not listed in the cbsa file -->
<!-- # unique(tracts_sf$fips[!tracts_sf$fips %in% cbsa$fips]) -->

<!-- tracts_sf %<>%  -->
<!--   left_join(cbsa) %>%  -->
<!--   mutate(cbsa = if_else(is.na(cbsa), COUNTYFP, cbsa),  -->
<!--          cbsa_name = if_else(is.na(cbsa_name), fips, cbsa_name) -->
<!--          ) %>%  -->
<!--   group_by(cbsa) %>%  -->
<!--   mutate(pop_cbsa = sum(pop)) %>%  -->
<!--   ungroup() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # recover population and area from tracts and add to flares data -->
<!-- # add parcels and density -->
<!-- flares %<>%  -->
<!--   left_join( -->
<!--     tracts_sf %>%  -->
<!--       st_drop_geometry() %>%  -->
<!--       select(GEOID, area) -->
<!--     ) %>%  -->
<!--   mutate(parcels = flares * 1200) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- # recover population and area from tracts and add to dispersion data -->
<!-- # add parcels -->
<!-- dispersion %<>%  -->
<!--   rename(GEOID = id,  -->
<!--          date = start_day) %>%  -->
<!--   left_join( -->
<!--     tracts_sf %>%  -->
<!--       st_drop_geometry() %>%  -->
<!--       select(GEOID, area) -->
<!--     ) %>%  -->
<!--   mutate(parcels = count * weight)  -->
<!-- ``` -->

<!-- Daily time series -->

<!-- ```{r} -->
<!-- daily_flares <- flares %>%  -->
<!--   group_by(date) %>%  -->
<!--   summarise(parcels = sum(parcels)) -->

<!-- daily_dispersion <- dispersion %>%  -->
<!--   group_by(date) %>%  -->
<!--   summarise(parcels = sum(parcels)) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- daily_flares %>%  -->
<!-- ggplot() +  -->
<!--   geom_line(aes(x = date, y = parcels, color = parcels)) + -->
<!--   theme_cowplot() +  -->
<!--   labs(title = "Daily total parcels", x = "") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- daily_dispersion %>%  -->
<!-- ggplot() +  -->
<!--   geom_line(aes(x = date, y = parcels, color = parcels)) + -->
<!--   theme_cowplot() +  -->
<!--   labs(title = "Daily total parcels", x = "") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- daily_comparison <- daily_flares %>%  -->
<!--   rename(source_parcels = parcels) %>%   -->
<!--   left_join(daily_dispersion %>%  -->
<!--               rename(target_parcels = parcels)) %>%  -->
<!--   mutate(diff = target_parcels - source_parcels) -->
<!-- daily_comparison -->
<!-- ``` -->

<!-- ```{r} -->
<!-- unique(daily_comparison$date[!daily_comparison$diff == 0]) -->
<!-- ``` -->
