
```{r}
library(tidyverse)
library(magrittr)
library(sf)
library(USAboundariesData)

particles <- read_rds("../data/particles.rds")
particles <- st_as_sf(particles)
class(particles)
```

```{r}
head(particles)
```

<!-- ```{python} -->
<!-- import wget -->
<!-- from zipfile import ZipFile -->
<!-- import os -->

<!-- url = 'https://www2.census.gov/geo/tiger/TIGER2016/TRACT/tl_2016_48_tract.zip' -->
<!-- wget.download(url, os.path.expanduser('~/tmp')) -->
<!-- file_name = os.path.expanduser('~/tmp/tl_2016_48_tract.zip') -->
<!-- ZipFile(file_name, 'r').extractall(os.path.expanduser('~/tmp/tl_2016_48_tract/')) -->
<!-- os.system("ls ~/tmp/tl_2016_48_tract/") -->
<!-- ``` -->

```{r, include=FALSE}
#### read tracts shapefile
tracts_sf <- st_read("~/tmp/tl_2016_48_tract/tl_2016_48_tract.shp")
tracts_sf <- tracts_sf %>% 
  dplyr::filter(STATEFP == "48")
crs_ <- "+proj=aea +lat_1=20 +lat_2=60 +lat_0=40 +lon_0=-96 +x_0=0 +y_0=0 +ellps=GRS80 +datum=NAD83 +units=m"
tracts_sf <- st_transform(tracts_sf, crs_)
```

```{r}
counties = USAboundaries::us_counties()
counties %<>% 
  select(-state_name) %>% 
  filter(statefp == "48")
counties <- st_transform(counties, crs_)
counties
```

## 3 month exposure

```{r}
tracts_sf$count <- lengths(st_intersects(tracts_sf, particles))

library(viridis)
library(cowplot)
ggplot() +
  geom_sf(data = tracts_sf, aes(fill = count), size = 0.001) + 
  scale_fill_viridis(option = "B", alpha = 0.8) + 
  theme_cowplot()
```

trim zero and above pbl

```{r}
particles_trim <- particles %>% 
  filter(height > 0, 
         height <= 2665)

tracts_sf$count <- lengths(st_intersects(tracts_sf, particles_trim))

ggplot() +
  geom_sf(data = tracts_sf, aes(fill = count), size = 0.001) + 
  scale_fill_viridis(option = "B", alpha = 0.8) + 
  theme_cowplot()
```

```{r}
counties$count <- lengths(st_intersects(counties, particles_trim))

ggplot() +
  geom_sf(data = counties, aes(fill = count), size = 0.001) + 
  scale_fill_viridis(option = "B", alpha = 0.8) + 
  theme_cowplot()
```

## weekly density

```{r}
library(lubridate)
particles %<>% 
  mutate(week = lubridate::week(Pdate))

particles_trim %<>% 
  mutate(week = lubridate::week(Pdate))

table(particles$week)
table(particles_trim$week)
```

```{r}
p <- list()
for(x in unique(particles$week)) {
  xx <- particles_trim %>% 
    filter(week == x)
  tracts_sf$density <- lengths(st_intersects(tracts_sf, xx)) / 
  as.numeric(st_area(tracts_sf)) * 1e6

p[[x]] <- ggplot() +
  geom_sf(data = tracts_sf, aes(fill = density), size = 0.001) + 
  scale_fill_viridis(option = "B", alpha = 0.8) + 
  theme_cowplot()
}
p
```

## how far do they go

```{r}
p <- list()
for(x in unique(particles$hour)) {
  xx <- particles_trim %>% 
    filter(hour == x)
  tracts_sf$density <- lengths(st_intersects(tracts_sf, xx)) / 
  as.numeric(st_area(tracts_sf)) * 1e6

p[[x]] <- ggplot() +
  geom_sf(data = tracts_sf, aes(fill = density), size = 0.001) + 
  scale_fill_viridis(option = "B", alpha = 0.8) + 
  theme_cowplot()
}
p
```
